"""Thermal model — radiative cooling in vacuum.

In space, heat can only be shed via radiation (Stefan-Boltzmann law).
No convection, no conduction to environment. This constrains compute.
"""

from dataclasses import dataclass
from typing import Optional

# Stefan-Boltzmann constant (W/m²/K⁴)
STEFAN_BOLTZMANN = 5.670374419e-8


@dataclass
class ThermalConfig:
    """Thermal subsystem configuration."""
    radiator_area_m2: float = 4.0        # Radiator surface area
    radiator_emissivity: float = 0.90    # Emissivity (1.0 = perfect blackbody)
    thermal_mass_j_per_k: float = 50000  # Thermal mass (J/K) — how quickly temp changes
    max_temp_c: float = 85.0             # Max operating temperature (°C)
    min_temp_c: float = -20.0            # Min operating temperature (°C)
    compute_temp_limit_c: float = 75.0   # Throttle compute above this
    ambient_space_k: float = 3.0         # Deep space background (3K CMB)
    earth_ir_w_m2: float = 240.0         # Earth IR flux on radiator (LEO, nadir-facing)
    solar_absorptivity: float = 0.20     # How much solar flux is absorbed


@dataclass
class ThermalState:
    """Current thermal state."""
    temp_c: float                  # Current temperature (°C)
    heat_generated_w: float        # Heat from compute + housekeeping
    heat_radiated_w: float         # Heat shed by radiators
    net_heat_w: float              # Generated - radiated
    can_compute: bool              # Below thermal limit
    throttle_pct: float            # How much to throttle (0=none, 1=full stop)


class ThermalModel:
    """Simulates satellite thermal state."""

    def __init__(self, config: Optional[ThermalConfig] = None, initial_temp_c: float = 25.0):
        self.config = config or ThermalConfig()
        self.temp_k = initial_temp_c + 273.15

    def step(self, dt_seconds: float, heat_load_w: float, in_eclipse: bool) -> ThermalState:
        """Advance thermal model by dt_seconds.

        Args:
            dt_seconds: Time step
            heat_load_w: Heat generated by compute + housekeeping (W)
            in_eclipse: Whether in Earth's shadow (affects solar heating)
        """
        c = self.config

        # Heat input from compute
        q_compute = heat_load_w

        # Solar heating on radiator (0 in eclipse)
        q_solar = 0.0 if in_eclipse else c.solar_absorptivity * 1361.0 * c.radiator_area_m2 * 0.25

        # Earth IR heating
        q_earth = c.earth_ir_w_m2 * c.radiator_area_m2 * 0.5  # Approximate view factor

        # Radiative cooling (Stefan-Boltzmann)
        q_radiated = c.radiator_emissivity * STEFAN_BOLTZMANN * c.radiator_area_m2 * (
            self.temp_k**4 - c.ambient_space_k**4
        )

        # Net heat
        q_net = q_compute + q_solar + q_earth - q_radiated

        # Temperature change
        delta_t = (q_net * dt_seconds) / c.thermal_mass_j_per_k
        self.temp_k += delta_t

        temp_c = self.temp_k - 273.15

        # Throttle calculation
        if temp_c >= c.max_temp_c:
            throttle = 1.0
        elif temp_c >= c.compute_temp_limit_c:
            throttle = (temp_c - c.compute_temp_limit_c) / (c.max_temp_c - c.compute_temp_limit_c)
        else:
            throttle = 0.0

        return ThermalState(
            temp_c=temp_c,
            heat_generated_w=q_compute + q_solar + q_earth,
            heat_radiated_w=q_radiated,
            net_heat_w=q_net,
            can_compute=temp_c < c.compute_temp_limit_c,
            throttle_pct=throttle,
        )

    def max_sustainable_heat_w(self, target_temp_c: float = 70.0) -> float:
        """Calculate max continuous heat load for a target equilibrium temperature."""
        c = self.config
        target_k = target_temp_c + 273.15
        q_rad = c.radiator_emissivity * STEFAN_BOLTZMANN * c.radiator_area_m2 * (
            target_k**4 - c.ambient_space_k**4
        )
        # Subtract environmental heating (worst case: sunlit)
        q_solar = c.solar_absorptivity * 1361.0 * c.radiator_area_m2 * 0.25
        q_earth = c.earth_ir_w_m2 * c.radiator_area_m2 * 0.5
        return max(0.0, q_rad - q_solar - q_earth)
